export const GET_PRODUCT_LOADING= 'GET_PRODUCT_LOADING';
export const GET_PRODUCT_ERROR= 'GET_PRODUCT_ERROR';
export const GET_PRODUCT_SUCCESS= 'GET_PRODUCT_SUCCESS';

export const ADD_PRODUCT_LOADING= 'ADD_PRODUCT_LOADING';
export const ADD_PRODUCT_ERROR= 'ADD_PRODUCT_ERROR';
export const ADD_PRODUCT_SUCCESS= 'ADD_PRODUCT_SUCCESS';


export const GET_SINGLEPRODUCT_LOADING= 'GET_SINGLEPRODUCT_LOADING';
export const GET_SINGLEPRODUCT_ERROR= 'GET_SINGLEPRODUCT_ERROR';
export const GET_SINGLEPRODUCT_SUCCESS= 'GET_SINGLEPRODUCT_SUCCESS';

export const UPDATE_PRODUCT_LOADING= 'UPDATE_PRODUCT_LOADING';
export const UPDATE_PRODUCT_ERROR= 'UPDATE_PRODUCT_ERROR';
export const UPDATE_PRODUCT_SUCCESS= 'UPDATE_PRODUCT_SUCCESS';

export const DELETE_PRODUCT_LOADING= 'DELETE_PRODUCT_LOADING';
export const DELETE_PRODUCT_ERROR= 'DELETE_PRODUCT_ERROR';
export const DELETE_PRODUCT_SUCCESS= 'DELETE_PRODUCT_SUCCESS';